import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = fileURLToPath(new URL('..', import.meta.url));
const outputFile = resolve(projectRoot, 'js/app.bundle.js');

// 按依赖顺序拼接模块，生成可被 file:// 页面直接加载的经典脚本。
const modules = [
    'js/utils.js',
    'data/pinyin-data.js',
    'data/words-data.js',
    'data/voice-map.js',
    'data/voice-manifest.js',
    'js/api.js',
    'js/storage.js',
    'js/audio.js',
    'js/keyboard.js',
    'js/letters.js',
    'js/pinyin.js',
    'js/words.js',
    'js/game.js',
    'js/main.js'
];

const source = [];
source.push('/* Generated by scripts/build-legacy.mjs. Edit source modules instead. */');

for (const modulePath of modules) {
    const file = await readFile(resolve(projectRoot, modulePath), 'utf8');
    const classicModule = file
        .replace(/^import .*?;\s*$/gm, '')
        .replace(/^export const /gm, 'const ');
    source.push(`\n/* --- ${modulePath} --- */\n${classicModule}`);
}

await mkdir(dirname(outputFile), { recursive: true });
await writeFile(outputFile, `${source.join('\n')}\n`, 'utf8');
console.log(`运行包已生成: ${outputFile}`);
